name: Generate Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate PlantUML Diagrams
      uses: cloudbees/plantuml-github-action@v1
      with:
        args: -v -tsvg docs/architecture/c4/*.puml

    - name: Move generated SVGs
      run: |
        mkdir -p docs/images
        mv docs/architecture/c4/*.svg docs/images/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
